### ISSUE TITLE
Platform does not support 'port:' option

### ISSUE THREAD

**Issue by peregrinus** [custom-components/sensor.unifigateway#16]
## The problem
The integration does not support the option to specify the listening port of the admin URL. Many people run this system under Docker and the requirement to only listen on 8443 is limiting.

When the port is specified in the 'host:' section home assistant simply appends :8443 to the address.

## Environment
arch | x86_64
dev | false
docker | true
hassio | false
os_name | Linux
os_version | 4.15.0-91-generic
python_version | 3.7.7
version | 0.107.7
virtualenv | false
- Home Assistant Core release with the issue: All
- Last working Home Assistant Core release (if known): None
- Operating environment (Home Assistant/Supervised/Docker/venv):  Docker

## Problem-relevant `configuration.yaml`
```yaml
  platform: unifigateway
  host: 10.x.x.x
  username: oliver
  password: *******
  monitored_conditions:
    - wlan
    - alerts
    - firmware
```

## Traceback/Error logs
```txt
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 380, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/url.py", line 392, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 3, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: https://10.x.x.x:8446:8443/api/login
```

**Comment by peregrinus** [comment]
If anyone else is interested, i was able to update the port section of the sensor.py file in the custom component folder as a temporary solution:

![image](https://user-images.githubusercontent.com/1098005/78315379-8be1ad80-75a8-11ea-9160-104fe95bd4e5.png)
