### ISSUE TITLE
Unifi Cloudkey firmware 2.0.24 support

### ISSUE THREAD

**Issue by davidvf** [custom-components/sensor.unifigateway#22]
Hi, after upgrading my unifi cloudkey to firmware version 2.0.24 the integration with hass is broken.

```Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f8917e15b80>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='192.168.0.5', port=8443): Max retries exceeded with url: /api/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8917e15b80>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/unifigateway/sensor.py", line 84, in setup_platform
    ctrl = Controller(host, username, password, port, version='v4',
  File "/usr/local/lib/python3.8/site-packages/pyunifi/controller.py", line 89, in __init__
    self._login()
  File "/usr/local/lib/python3.8/site-packages/pyunifi/controller.py", line 137, in _login
    r = self.session.post(login_url, json=params)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='192.168.0.5', port=8443): Max retries exceeded with url: /api/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8917e15b80>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

in the configuration.yaml i have tried to set 
`version: unifiOS`
but that gives me another error:

`Invalid config for [sensor.unifigateway]: [version] is an invalid option for [sensor.unifigateway]. Check: sensor.unifigateway->version. (See /config/sensors.yaml, line 36). Please check the docs at https://github.com/custom-components/sensor.unifigateway`

**Comment by deliwyn** [comment]
`urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='192.168.0.5', port=8443)`

Have you tried to change the port number to 443? Since FW 2.0.24, the port has switched from 8443 to standard 443.

However, I tried to install the UniFi Gateway custom component and it doesn't work on my side, even using 443 in the configuration. My UniFi CK firmware version is 2.0.26.

**Comment by davidvf** [comment]
Indeed i've also tried port 443. In the meantime i am also running fw version 2.0.26 but the integration is still broken.

**Comment by ahmaddxb** [comment]
I get this error now but credential are correct

Logger: custom_components.unifigateway.sensor
Source: custom_components/unifigateway/sensor.py:91
Integration: unifigateway (documentation)
First occurred: 12:49:30 (1 occurrences)
Last logged: 12:49:30

Failed to connect to Unifi Security Gateway: Login failed - status code: 401

**Comment by Tamsy** [comment]
Unfortunately I can confirm this too:
Finally updated my UniFi UCK-G2+ from Fw 1.1.13 to 2.0.27. Since on the new Firmware sensor.unifigateway is not working anymore. Changing the port numer accordingly and setting "version" from v5 to unifiOS makes no difference.

**Comment by jamieshaw** [comment]
Seems as though an update has been pushed for _unifigateway_ as 0.3.3, but this does not seem to make any changes in accessing my Cloud Key with the following config.  Still receiving `[homeassistant.components.sensor] Error while setting up unifigateway platform for sensor` during platform init.

### Configuration
```yaml
platform: unifigateway
host: !secret unifi_network_host
port: 443
username: !secret unifi_network_user
password: !secret unifi_network_pass
version: 'unifiOS'
site_id: 'default'
verify_ssl: true
```

**Comment by jamieshaw** [comment]
Can confirm that I can connect to UCK2+ on 2.0.24 when using _unifigateway_ 0.3.3 with version configured to `UDMP-unifiOS`.
