### ISSUE TITLE
Sensors not available after upgrade

### ISSUE THREAD

**Issue by Drewskieza** [custom-components/sensor.unifigateway#36]
I just upgraded to the new version (0.3.2) but now my sensors are not available and I have the below my log file.
Home Assistant OS 5.12
supervisor-2021.03.6
core-2021.3.4
Reverted back to 0.2.3 and all works again.

`2021-03-24 15:58:26 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up unifigateway platform for sensor
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 200, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/unifigateway/sensor.py", line 88, in setup_platform
    ctrl = Controller(host, username, password, port, version,
  File "/usr/local/lib/python3.8/site-packages/pyunifi/controller.py", line 113, in __init__
    self._login()
  File "/usr/local/lib/python3.8/site-packages/pyunifi/controller.py", line 161, in _login
    r = self.session.post(login_url, json=params)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))`

**Comment by BartEngelen** [comment]
I have the same issue

**Comment by zissou1** [comment]
Same for me

**Comment by skank01** [comment]
Same for me

**Comment by roodbaard80** [comment]
I do have the same issue. I added this to my config, but no difference.
    version: unifiOS

I now get this error:
2021-03-25 15:22:22 ERROR (SyncWorker_5) [custom_components.unifigateway.sensor] Failed to connect to Unifi Security Gateway: Login failed - status code: 405

**Comment by Zoriontsu** [comment]
Same issue here. Went back to 2.3

**Comment by cuihaijun** [comment]
port: 8443

**Comment by cuihaijun** [comment]
> 我刚刚升级到新版本（0.3.2），但是现在我的传感器不可用，并且在我的日志文件下面。
> Home Assistant OS 5.12
> Supervisor-2021.03.6
> core-2021.3.4
> 恢复到0.2.3 ，然后又可以正常工作。
> 
> `2021-03-24 15:58:26错误（MainThread）[homeassistant.components.sensor]为传感器
> Traceback设置unifigateway平台时出错（最近一次调用为最新）：
> 文件“ /usr/local/lib/python3.8 /site-packages/urllib3/connectionpool.py“，第699行，位于urlopen
> httplib_response = self._make_request（
> 文件” /usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py“，第445行，在_make_request
> six.raise_from（e，None）
> 文件“”中，第3行，在raise_from
> 文件“ /usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py”，第440行中，在_make_request中，
> httplib_response = conn.getresponse（）
> 文件“ /usr/local/lib/python3.8/http/client.py”，行1347，在getresponse
> response.begin（）中
> 文件“ /usr/local/lib/python3.8/http/client.py”，第307行，开始
> 版本，状态，原因= self._read_status（）
> 文件“ /usr/local/lib/python3.8/http” /client.py”，第268行，在_read_status中，
> 行= str（self.fp.readline（_MAXLINE + 1），“ iso-8859-1”）
> 文件“ /usr/local/lib/python3.8/socket.py “，行669，在readinto中
> 返回self._sock.recv_into（b）
> 文件” /usr/local/lib/python3.8/ssl.py“，行1241，在recv_in中，
> 返回self.read（nbytes，buffer）
> 文件” /usr/local/lib/python3.8/ssl.py“，行1099，在读取
> 返回self._sslobj.read（len，buffer）
> ConnectionResetError：[Errno 104]对等重置连接
> 
> 在处理上述异常期间，发生了另一个异常：
> 
> 追溯（最近一次通话最后一次）：
> 文件“ /usr/local/lib/python3.8/site-packages/requests/adapters.py”，行439，在send
> resp = conn.urlopen（
> 文件“ / usr / local / urlopen中的lib / python3.8 / site-packages / urllib3 / connectionpool.py“，行755
> retries = retries.increment（
> 文件” /usr/local/lib/python3.8/site-packages/urllib3/util/retry “ .py”，第531行，增量
> 为6。reraise（类型（错误），错误，_stacktrace）
> 文件“ /usr/local/lib/python3.8/site-packages/urllib3/packages/six.py”，行734，在
> 提高值中。with_traceback（tb）
> 文件“ /usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py”，行699，在urlopen中，
> httplib_response = self._make_request（
> _make_request
> six中的文件“ /usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py”第445行。raise_from（e，None）
> 在
> 文件“ / usr”中的文件“”，第3行，raise_from /local/lib/python3.8/site-packages/urllib3/connectionpool.py”，第440行，_make_request中的
> httplib_response = conn.getresponse（）
> 文件“ /usr/local/lib/python3.8/http/client.py” “，在getresponse
> response.begin（）
> 文件中的第1347行，” / usr / local / lib / python3.8 / http / client.py “，在开始
> 版本中的第307行，状态，原因= self._read_status（）
> 文件” /usr/local/lib/python3.8/http/client.py”，第268行，在_read_status中，
> 行= str（self.fp.readline（_MAXLINE + 1），“ iso-8859-1”）
> 文件“/read/local/lib/python3.8/socket.py“，行669，读入
> 在recv_in中返回self._sock.recv_into（b）
> 文件“ /usr/local/lib/python3.8/ssl.py”，行1241，
> 返回self.read（nbytes，buffer）
> 文件“ / usr / local / lib / python3.8 / ssl.py“，行1099，在读取
> 返回self._sslobj.read（len，buffer）
> urllib3.exceptions.ProtocolError：（'Connection aborted。'，ConnectionResetError（104，'对等重置连接'））
> 
> 在处理上述异常期间，发生了另一个异常：
> 
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 200, in _async_setup_platform
> await asyncio.shield(task)
> File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
> result = self.fn(*self.args, **self.kwargs)
> File "/config/custom_components/unifigateway/sensor.py", line 88, in setup_platform
> ctrl = Controller(host, username, password, port, version,
> File "/usr/local/lib/python3.8/site-packages/pyunifi/controller.py", line 113, in **init**
> self._login()
> File "/usr/local/lib/python3.8/site-packages/pyunifi/controller.py", line 161, in _login
> r = self.session.post(login_url, json=params)
> File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
> return self.request('POST', url, data=data, json=json, **kwargs)
> File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
> resp = self.send(prep, **send_kwargs)
> File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
> r = adapter.send(request, **kwargs)
> File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
> raise ConnectionError(err, request=request)
> requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))`

port: 8443

**Comment by guy0nabuffalo** [comment]
I also lost my sensors and noticed Im getting a login failed error as well. For now Ive went back to v0.2.3 and manually added version to the manifest file. All is working again.

**Comment by kloggy** [comment]
Yes, same problem here...

**Comment by shammysha** [comment]
set port in your config

port: 8443

default port has beenchanged since 25 feb from 8443 to 443

**Comment by guy0nabuffalo** [comment]
Thanks for the heads up, I didnt realize. Updated in HACs to latest version and changed the port from 443 to 8443. All sensors working as expected.

**Comment by kloggy** [comment]
Yes, I knew this but have now explicitly added `port:8443` and it seems to work.
I'm slightly confused though because the documentation says it defaults to 8443:

---

**port**

(integer)(Optional) The port of your controller's web interface Default value: 8443

---

And the integration worked before with no port explicitly included in the config.

**Comment by shammysha** [comment]
I'm not author of changes
Just lookup in history . May be documentation does not include this changes

https://github.com/custom-components/sensor.unifigateway/commit/257e93276feecb3431c6f1ae60927b4ff93fcda3#diff-c9f220a52a9ce7491f7926b90e37fc5d86c31da79b86f52afe052edbeb1d17echttps://github.com/custom-components/sensor.unifigateway/commit/257e93276feecb3431c6f1ae60927b4ff93fcda3#diff-c9f220a52a9ce7491f7926b90e37fc5d86c31da79b86f52afe052edbeb1d17ec

**Comment by skank01** [comment]
Where do i fill in the port?
Is it 8443 now or 443
Here you say its 8443 and docu speaks that 8443 is gone, and now its 443

**Comment by skank01** [comment]
Edit : ah now i get it: default was 8443, the default changed to 443, so we have to use 8443 again
I added it, and now indeed sensors work, this van be closed i think !

**Comment by Drewskieza** [comment]
Just for clarity, this is how I got mine to work, so maybe just the documentation needs to be updated.

sensor:
  - platform: unifigateway
    host: unifi
    **port: 8443**
    username: username
    password: password
    monitored_conditions:
      - www
      - wlan
      - alerts
      - firmware
