### ISSUE TITLE
Unable to get sensor working via HACS Core-2021.6.3

### ISSUE THREAD

**Issue by CrouchingWorm** [custom-components/sensor.unifigateway#44]
Hi there,
Is used to use this as custom integration. Love it. Thanks very much.
I've since tried to use it since it was installed via HACS.
I simply un commented out the previous config, and it's failing to connect to my controller.
I'm running HAS on Debian (x86_64), with the Unifi Controller in a docker on the same machine. Current Version 0.23.1. Default ports. No cert installed.
I'm seeing this error in the HA logs:
````
Error while setting up unifigateway platform for sensor
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
````

Here's my configuration.yaml extract:
````
  - platform: unifigateway
#    host: 192.168.1.178
    username: Admin
    password: !secret unifi_gw_sysmon
    monitored_conditions:
      - www
      - wlan
      - lan
      - wan
#      - alerts
      - firmware
#      - vpn
````
I tried commenting out the host ip to see if that would help at all..

 What silly mistake am I making?

Thanks in advance,

**Comment by CrouchingWorm** [comment]
This is a duplicte. I'll attach to the other one.
